"""GraphRAG Interface.

Provides read access to the K-NN Semantic Graph generated by build_graph.py.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path
from dataclasses import dataclass
from typing import Any

from rag.embed import INDEX_DIR

DEFAULT_GRAPH_DIR = Path("data/index-sweep-450")

@dataclass
class EdgeResult:
    chunk_id: str
    doc_id: str
    title: str
    court: str
    score: float

class GraphDB:
    def __init__(self, index_dir: Path = DEFAULT_GRAPH_DIR):
        self.db_path = Path(index_dir) / "graph.db"
        if not self.db_path.exists():
            raise FileNotFoundError(f"Graph DB not found at {self.db_path}. Run scripts/build_graph.py first.")
            
        # Read-only connection for thread safety in FastAPI
        self.conn = sqlite3.connect(f"file:{self.db_path}?mode=ro", uri=True, check_same_thread=False)
        self.conn.row_factory = sqlite3.Row

    def get_neighbors(self, chunk_id: str, limit: int = 5) -> list[EdgeResult]:
        """Fetch the most semantically related chunks for a given chunk."""
        cur = self.conn.cursor()
        cur.execute("""
            SELECT n.chunk_id, n.doc_id, n.title, n.court, e.score 
            FROM edges e
            JOIN nodes n ON e.target_id = n.chunk_id
            WHERE e.source_id = ?
            ORDER BY e.score DESC
            LIMIT ?
        """, (chunk_id, limit))
        
        rows = cur.fetchall()
        return [
            EdgeResult(
                chunk_id=r["chunk_id"],
                doc_id=r["doc_id"],
                title=r["title"],
                court=r["court"],
                score=r["score"]
            )
            for r in rows
        ]

    def close(self):
        self.conn.close()
